version: '3.8'

services:
  # SFU Server (Media Forwarding)
  sfu:
    build:
      context: .
      dockerfile: Dockerfile.sfu
    container_name: gryt-sfu-prod
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - STUN_SERVERS=${STUN_SERVERS:-stun:stun.l.google.com:19302}
    env_file:
      - ./sfu-v2/.env
    networks:
      - gryt-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5005/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Gryt Server (Signaling)
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: gryt-server-prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - SFU_WS_HOST=ws://sfu:5005
    env_file:
      - ./server/.env
    volumes:
      - ./server/public:/app/public:ro
    networks:
      - gryt-network
    depends_on:
      - sfu
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Web Client with Nginx
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: gryt-client-prod
    ports:
      - "80:80"
    networks:
      - gryt-network
    depends_on:
      - server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  gryt-network:
    driver: bridge
