version: '3.8'

services:
  # SFU Server (Media Forwarding)
  sfu:
    build:
      context: .
      dockerfile: Dockerfile.sfu
    container_name: gryt-sfu
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - STUN_SERVERS=stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302
    volumes:
      - ./sfu-v2/.env:/root/.env:ro
    networks:
      - gryt-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5005/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Gryt Server 1 (Signaling)
  server1:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: gryt-server-1
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - SERVER_NAME=Gryta Krutt
      - SERVER_ICON=example.png
      - SFU_WS_HOST=ws://sfu:5005
      - STUN_SERVERS=stun:stun.l.google.com:19302
      - CORS_ORIGIN=http://localhost:5173
      - SERVER_TOKEN=123
      - GRYT_AUTH_API=https://auth.gryt.chat
      - NODE_ENV=development
    volumes:
      - ./server/.env:/app/.env:ro
      - ./server/public:/app/public:ro
    networks:
      - gryt-network
    depends_on:
      - sfu
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Gryt Server 2 (Signaling)
  server2:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: gryt-server-2
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - SERVER_NAME=Techial
      - SERVER_ICON=example.png
      - SFU_WS_HOST=ws://sfu:5005
      - STUN_SERVERS=stun:stun.l.google.com:19302
      - CORS_ORIGIN=http://localhost:5173
      - SERVER_TOKEN=456
      - GRYT_AUTH_API=https://auth.gryt.chat
      - NODE_ENV=development
    volumes:
      - ./server/.env:/app/.env:ro
      - ./server/public:/app/public:ro
    networks:
      - gryt-network
    depends_on:
      - sfu
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Web Client
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: gryt-client
    ports:
      - "5173:80"
    environment:
      - VITE_GRYT_AUTH_API=https://auth.gryt.chat
    volumes:
      - ./client/.env:/app/.env:ro
    networks:
      - gryt-network
    depends_on:
      - server1
      - server2
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  gryt-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  sfu-data:
  server-data:
