apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gryt.fullname" . }}-config
  labels:
    {{- include "gryt.labels" . | nindent 4 }}
  {{- with (include "gryt.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  # SFU Configuration
  SFU_PORT: {{ .Values.sfu.service.port | quote }}
  STUN_SERVERS: {{ .Values.gryt.stun.servers | quote }}
  
  # Server Configuration
  SERVER_PORT: {{ .Values.server.service.port | quote }}
  NODE_ENV: {{ .Values.server.env.NODE_ENV | quote }}
  SERVER_NAME: {{ .Values.server.env.SERVER_NAME | quote }}
  SERVER_ICON: {{ .Values.server.env.SERVER_ICON | quote }}
  GRYT_AUTH_API: {{ .Values.gryt.auth.apiUrl | quote }}
  
  # Client Configuration
  VITE_GRYT_AUTH_API: {{ .Values.gryt.auth.apiUrl | quote }}
  VITE_WS_HOST: {{ include "gryt.client.wsHost" . | quote }}
  
  # Nginx Configuration
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
        
        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log warn;
        
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types
            text/plain
            text/css
            text/xml
            text/javascript
            application/json
            application/javascript
            application/xml+rss
            application/atom+xml
            image/svg+xml;
        
        server {
            listen 80;
            server_name _;
            root /usr/share/nginx/html;
            index index.html;
            
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header Referrer-Policy "no-referrer-when-downgrade" always;
            add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;
            
            location / {
                try_files $uri $uri/ /index.html;
            }
            
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
            }
            
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
        }
    } 