apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gryt.fullname" . }}-secrets
  labels:
    {{- include "gryt.labels" . | nindent 4 }}
  {{- with (include "gryt.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  # Server secrets (base64 encoded)
  SERVER_PASSWORD: {{ .Values.server.secrets.serverPassword | b64enc | quote }}
  SFU_WS_HOST: {{ include "gryt.sfu.wsHost" . | b64enc | quote }}
  CORS_ORIGIN: {{ include "gryt.corsOrigin" . | b64enc | quote }}

{{- if .Values.gryt.tls.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gryt.tls.secretName }}
  labels:
    {{- include "gryt.labels" . | nindent 4 }}
  {{- with (include "gryt.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
    {{- if .Values.gryt.tls.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.gryt.tls.certManager.issuer | quote }}
    {{- end }}
  {{- end }}
type: kubernetes.io/tls
data:
  # TLS certificate and key will be managed by cert-manager or provided manually
  {{- if not .Values.gryt.tls.certManager.enabled }}
  tls.crt: "" # Provide your certificate here (base64 encoded)
  tls.key: "" # Provide your private key here (base64 encoded)
  {{- end }}
{{- end }} 