{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gryt.serviceAccountName" . }}
  labels:
    {{- include "gryt.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "gryt.annotations" .) }}
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }} 